name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: write
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build.yml
