name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  attestations: write
  id-token: write
  artifact-metadata: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/build.yml
    with:
      publish: true